
  /*******************************************************************
  * Address.java
  * Generated by Backendless Corp.
  ********************************************************************/
		package eclipseapps.mobility.parkeame.backendservice.openpay;

public class Address
{
    private String city;
    private String countryCode;
    private String line1;
    private String line2;
    private String line3;
    private String postalCode;
    private String state;
    public void setCity(String city)
    {
      this.city = city;
    }
    public void setCountryCode(String countryCode)
    {
      this.countryCode = countryCode;
    }
    public void setLine1(String line1)
    {
      this.line1 = line1;
    }
    public void setLine2(String line2)
    {
      this.line2 = line2;
    }
    public void setLine3(String line3)
    {
      this.line3 = line3;
    }
    public void setPostalCode(String postalCode)
    {
      this.postalCode = postalCode;
    }
    public void setState(String state)
    {
      this.state = state;
    }
    public String getCity( )
    {
      return city;
    }
    public String getCountryCode( )
    {
      return countryCode;
    }
    public String getLine1( )
    {
      return line1;
    }
    public String getLine2( )
    {
      return line2;
    }
    public String getLine3( )
    {
      return line3;
    }
    public String getPostalCode( )
    {
      return postalCode;
    }
    public String getState( )
    {
      return state;
    }
}