
  /*******************************************************************
  * DemoComment.java
  * Generated by Backendless Corp.
  ********************************************************************/
		package eclipseapps.mobility.parkeame.backendservice;

public class DemoComment
{
    private String author;
    private String commentText;
    public void setAuthor(String author)
    {
      this.author = author;
    }
    public void setCommentText(String commentText)
    {
      this.commentText = commentText;
    }
    public String getAuthor( )
    {
      return author;
    }
    public String getCommentText( )
    {
      return commentText;
    }
}